/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/discord-membership/wrangler.jsonc --include-runtime=false --env-interface=MembershipEnv workers/discord-membership/worker-configuration.d.ts` (hash: 3f9e8f7064ff501aef08eb7484688963)
interface __BaseEnv_MembershipEnv {
	DISCORD_BOT_TOKEN: SecretsStoreSecret;
	WIKI_GUILD_ID: "737538781024092170";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_MembershipEnv {}
}
interface MembershipEnv extends __BaseEnv_MembershipEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WIKI_GUILD_ID">> {}
}

export type { MembershipEnv }
